export const GENEROS = [
  'ACAO',
  'AVENTURA',
  'RPG',
  'ESTRATEGIA',
  'ESPORTES',
  'CORRIDA',
  'LUTA',
  'FPS',
  'TPS',
  'SURVIVAL',
  'HORROR',
  'PLATAFORMA',
  'METROIDVANIA',
  'ROGUELIKE',
  'SIMULACAO',
  'PUZZLE',
  'STEALTH',
  'MUSICAL',
  'VISUAL_NOVEL',
  'MOBILE',
  'OUTROS',
]

export const PLATAFORMAS = [
  'PS4',
  'PS5',
  'XBOX_ONE',
  'XBOX_SERIES_X',
  'XBOX_SERIES_S',
  'PC',
  'NINTENDO_SWITCH',
  'MOBILE',
  'OUTROS',
]

export const GENERO_LABEL = {
  ACAO: 'Ação',
  AVENTURA: 'Aventura',
  RPG: 'RPG',
  ESTRATEGIA: 'Estratégia',
  ESPORTES: 'Esportes',
  CORRIDA: 'Corrida',
  LUTA: 'Luta',
  FPS: 'FPS',
  TPS: 'TPS',
  SURVIVAL: 'Survival',
  HORROR: 'Horror',
  PLATAFORMA: 'Plataforma',
  METROIDVANIA: 'Metroidvania',
  ROGUELIKE: 'Roguelike',
  SIMULACAO: 'Simulação',
  PUZZLE: 'Puzzle',
  STEALTH: 'Stealth',
  MUSICAL: 'Musical',
  VISUAL_NOVEL: 'Visual Novel',
  MOBILE: 'Mobile',
  OUTROS: 'Outros',
}

export const PLATAFORMA_LABEL = {
  PS4: 'PlayStation 4',
  PS5: 'PlayStation 5',
  XBOX_ONE: 'Xbox One',
  XBOX_SERIES_X: 'Xbox Series X',
  XBOX_SERIES_S: 'Xbox Series S',
  PC: 'PC',
  NINTENDO_SWITCH: 'Nintendo Switch',
  MOBILE: 'Mobile',
  OUTROS: 'Outros',
}