export const GENEROS = [
  'ACAO',
  'AVENTURA',
  'RPG',
  'ESTRATEGIA',
  'ESPORTES',
  'CORRIDA',
  'LUTA',
  'FPS',
  'TPS',
  'SURVIVAL',
  'HORROR',
  'PLATAFORMA',
  'METROIDVANIA',
  'ROGUELIKE',
  'SIMULACAO',
  'PUZZLE',
  'STEALTH',
  'MUSICAL',
  'VISUAL_NOVEL',
  'MOBILE',
  'OUTROS',
]

export const PLATAFORMAS = [
  'PC',
  'PLAYSTATION',
  'PLAYSTATION_2',
  'PLAYSTATION_3',
  'PLAYSTATION_4',
  'PLAYSTATION_5',
  'PLAYSTATION_PORTABLE',
  'PLAYSTATION_VITA',
  'XBOX',
  'XBOX_360',
  'XBOX_ONE',
  'XBOX_SERIES_X',
  'XBOX_SERIES_S',
  'NINTENDO_ENTERTAINMENT_SYSTEM',
  'SUPER_NINTENDO',
  'NINTENDO_64',
  'NINTENDO_GAMECUBE',
  'NINTENDO_WII',
  'NINTENDO_WII_U',
  'NINTENDO_SWITCH',
  'NINTENDO_SWITCH_2',
  'GAME_BOY',
  'GAME_BOY_ADVANCE',
  'NINTENDO_DS',
  'NINTENDO_3DS',
  'MOBILE',
  'OUTROS',
]

export const GENERO_LABEL = {
  ACAO: 'Ação',
  AVENTURA: 'Aventura',
  RPG: 'RPG',
  ESTRATEGIA: 'Estratégia',
  ESPORTES: 'Esportes',
  CORRIDA: 'Corrida',
  LUTA: 'Luta',
  FPS: 'FPS',
  TPS: 'TPS',
  SURVIVAL: 'Survival',
  HORROR: 'Horror',
  PLATAFORMA: 'Plataforma',
  METROIDVANIA: 'Metroidvania',
  ROGUELIKE: 'Roguelike',
  SIMULACAO: 'Simulação',
  PUZZLE: 'Puzzle',
  STEALTH: 'Stealth',
  MUSICAL: 'Musical',
  VISUAL_NOVEL: 'Visual Novel',
  MOBILE: 'Mobile',
  OUTROS: 'Outros',
}

export const PLATAFORMA_LABEL = {
  PC: 'PC',
  PLAYSTATION: 'PlayStation',
  PLAYSTATION_2: 'PlayStation 2',
  PLAYSTATION_3: 'PlayStation 3',
  PLAYSTATION_4: 'PlayStation 4',
  PLAYSTATION_5: 'PlayStation 5',
  PLAYSTATION_PORTABLE: 'PlayStation Portable',
  PLAYSTATION_VITA: 'PlayStation Vita',
  XBOX: 'Xbox',
  XBOX_360: 'Xbox 360',
  XBOX_ONE: 'Xbox One',
  XBOX_SERIES_X: 'Xbox Series X',
  XBOX_SERIES_S: 'Xbox Series S',
  NINTENDO_ENTERTAINMENT_SYSTEM: 'Nintendo Entertainment System',
  SUPER_NINTENDO: 'Super Nintendo',
  NINTENDO_64: 'Nintendo 64',
  NINTENDO_GAMECUBE: 'Nintendo GameCube',
  NINTENDO_WII: 'Nintendo Wii',
  NINTENDO_WII_U: 'Nintendo Wii U',
  NINTENDO_SWITCH: 'Nintendo Switch',
  NINTENDO_SWITCH_2: 'Nintendo Switch 2',
  GAME_BOY: 'Game Boy',
  GAME_BOY_ADVANCE: 'Game Boy Advance',
  NINTENDO_DS: 'Nintendo DS',
  NINTENDO_3DS: 'Nintendo 3DS',
  MOBILE: 'Mobile',
  OUTROS: 'Outros',
}